# Generated by Django 3.0.3 on 2020-06-14 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AddField(
            model_name='artist',
            name='a_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='a_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='a_img',
            field=models.ImageField(blank=True, upload_to='artists'),
        ),
    ]
