# Generated by Django 3.0.3 on 2020-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0002_auto_20200614_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='a_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
