# Generated by Django 3.0.3 on 2020-06-17 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0003_artist_a_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery1',
            fields=[
                ('g1_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g1_img', models.ImageField(blank=True, upload_to='gallery1')),
            ],
        ),
        migrations.CreateModel(
            name='gallery2',
            fields=[
                ('g2_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g2_img', models.ImageField(blank=True, upload_to='gallery2')),
            ],
        ),
        migrations.CreateModel(
            name='gallery3',
            fields=[
                ('g3_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g3_img', models.ImageField(blank=True, upload_to='gallery3')),
            ],
        ),
        migrations.CreateModel(
            name='gallery4',
            fields=[
                ('g4_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g4_img', models.ImageField(blank=True, upload_to='gallery4')),
            ],
        ),
    ]
