# Generated by Django 3.0.3 on 2020-06-17 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0004_gallery1_gallery2_gallery3_gallery4'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_work',
            fields=[
                ('w_id', models.UUIDField(default=uuid.UUID('7f5ab1f4-75fe-47e6-b2c4-c58ab2123f1e'), editable=False, primary_key=True, serialize=False)),
                ('w_img', models.ImageField(upload_to='work')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tattoo_heritage.Artist')),
            ],
        ),
    ]
