# Generated by Django 3.0.3 on 2020-06-23 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0006_auto_20200623_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='a_des',
            field=models.CharField(default='This is tattoo artist.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist_work',
            name='w_id',
            field=models.UUIDField(default=uuid.UUID('798cd602-3b54-459a-8a2d-405d2e6c44d3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
