# Generated by Django 3.0.3 on 2020-06-23 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_heritage', '0008_auto_20200623_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_work',
            name='w_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
